### ISSUE TITLE
Your target is too far away!

### ISSUE THREAD

**Issue by patritha** [Kikugie/unnamed-cannon-setup-mod#1]
no matter what I do it always says "your target is too far away!". I hope i set it up correctly because i wasnt given Pt.txt or Ct.txt so i just made blank files with the names. I also set the origin correctly. please help

**Comment by ROBLOXgamer260** [comment]
had the same issue, the txt files are in here https://www.mediafire.com/folder/yci3ip29bpu36/Smart_Artillery

**Comment by patritha** [comment]
that fixed it thank you so much!
